### ISSUE TITLE
store crashes when serializing null relationship

### ISSUE THREAD

**Issue by jamesdixon** [beauby/jsonapi-datastore#12]
When attempting to serialize an object with a `null` relationship, the `serialize()` method crashed. I was going to make a PR, but my fork is already a bit customized to serialize the store to an object that doesn't contain any of the store methods so I can pass it to my ORM. 

That said, I've tracked the issue down to [this line](https://github.com/beauby/jsonapi-datastore/blob/master/src/jsonapi-datastore.js#L47). Essentially, `self[key]` is `undefined` when a `null` relationship is serialized, which causes the crash. This bit of code appears to fix it:

```javascript
    if (self[key]) {
        if (self[key].constructor === Array) {
          res.data.relationships[key] = {
            data: self[key].map(relationshipIdentifier)
          };
        } else {
          res.data.relationships[key] = {
            data: relationshipIdentifier(self[key])
          };
        }
      } else {
        res.data.relationships[key] = null;
      }
```

I haven't fully tested, but just wanted to give a heads up. Thanks for building a great library!

**Comment by beauby** [comment]
Thanks for the heads up, will fix ASAP.
