### ISSUE TITLE
Error: Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by mklocek** [beauby/jsonapi-datastore#15]
Exporting module:
```
module.exports = {
  JsonApiDataStore: JsonApiDataStore,
  JsonApiDataStoreModel: JsonApiDataStoreModel
};
```
Not works in non-nodejs and non-browserify environments. There is no need to always use requirejs and stuff like that. I'm suggesting add `module` existance check. I'm ready to create PR if you agree.

**Comment by beauby** [comment]
Agreed. It was the case pre-es6 translation. Would love a PR.

Le vendredi 20 novembre 2015, Marcin Klocek <notifications@github.com> a
écrit :

> Exporting module:
>
> module.exports = {
>   JsonApiDataStore: JsonApiDataStore,
>   JsonApiDataStoreModel: JsonApiDataStoreModel
> };
>
> Not works in non-nodejs and non-browserify environments. There is no need
> to always use requirejs and stuff like that. I'm suggesting add module
> existance check. I'm ready to create PR if you agree.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/beauby/jsonapi-datastore/issues/15>.
>


-- 
Lucas Hosseini
lucas.hosseini@gmail.com
