### ISSUE TITLE
Angular - Create new 'Article' Model before initial sync

### ISSUE THREAD

**Issue by plwade** [beauby/jsonapi-datastore#21]
I have a situation where I would like to create a new 'Article' before I have queried my restAPI and sync'd the results.

This means the following line will not find 'article' in the Model store, because we have not performed an initial sync.
var newArticle = new JsonApiDataStore.Model('article');

Any idea how to do this?

Any help appreciated.

Regards,

Paul.

**Comment by beauby** [comment]
Currently what you could do is:
```javascript
// c.f. https://github.com/beauby/jsonapi-datastore/blob/master/src/jsonapi-datastore.js#L10
var newArticle = new JsonApiDataStoreModel('article');
newArticle.setAttribute('title', 'Cool Article');
// ...
newArticle.setRelationship('author', user);
// ...
```

**Comment by plwade** [comment]
Hi Lucas, 
Thank you for getting back to me so soon:)
We have just started developing an Angular app, and it is my job to evaluate the client libraries and get our front end talking to our back end api, so your help is much appreciated.
I may have a few more questions along the way, so it would be good if we could stay in touch.
Thanks for the help.
Regards, Paul.

**Comment by beauby** [comment]
Hi Paul, 
No worries, feel free to open as many issues as necessary.
Cheers,
Lucas

**Comment by plwade** [comment]
Much appreciated:)Thank you.Paul.

Date: Sun, 27 Dec 2015 14:41:59 -0800
