### ISSUE TITLE
Please bump bower version

### ISSUE THREAD

**Issue by iamchrismiller** [beauby/jsonapi-datastore#23]
Looks like `https://github.com/beauby/jsonapi-datastore/commit/c18a3ea853ca6cee134bfaa6044544bfefbffa79` commit is missing and this causes issues in an ES6 environment as module is not defined. 

Current workaround : 
`bower install git://github.com/beauby/jsonapi-datastore#021e464fd89eb34a77416db1f7f0785ef57b93ef`

Thanks

**Comment by beauby** [comment]
Hi Chris,

Thanks for pointing that out – will take care of it tomorrow.

Cheers,

Lucas

On Tuesday, 16 February 2016, Chris Miller <notifications@github.com> wrote:

> Looks like
> https://github.com/beauby/jsonapi-datastore/commit/c18a3ea853ca6cee134bfaa6044544bfefbffa79
> commit is missing and this causes issues in an ES6 environment as module is
> not defined.
>
> Current workaround :
> bower install git://
> github.com/beauby/jsonapi-datastore#021e464fd89eb34a77416db1f7f0785ef57b93ef
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/beauby/jsonapi-datastore/issues/23>.
>


-- 
Lucas Hosseini
lucas.hosseini@gmail.com

**Comment by beauby** [comment]
Sorry about the delay – just bumped it.

**Comment by dmarkow** [comment]
@beauby Any chance of getting 0.4.0 published to npm as well? Thanks!

**Comment by beauby** [comment]
@dmarkow Just did. Sorry for the inconvenience, the Travis hook for auto-publishing seems to have failed when I tagged v0.4.0.

**Comment by dmarkow** [comment]
@beauby No worries, I appreciate your work on this package :+1:
