### ISSUE TITLE
TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by krainboltgreene** [beauby/jsonapi-datastore#25]
```
syncRecord = this.syncRecord.bind(this);
```

**Comment by beauby** [comment]
Hi @krainboltgreene, could you give a bit more context about when this error happens?

**Comment by krainboltgreene** [comment]
After looking it appears to happen when I give a full json api payload, where the root keys are `data` and `links`. However, when I give it just the `data` value I receive back an empty array.

**Comment by beauby** [comment]
Could you provide an example of a failing payload?

**Comment by krainboltgreene** [comment]
Sure: https://gist.github.com/krainboltgreene/7184be7382e14284797a

**Comment by beauby** [comment]
Ok so I just tested locally and it worked. Could you confirm this payload is failing on your end and describe your exec environment?

**Comment by krainboltgreene** [comment]
I can do you one better, here's the repository: https://github.com/lacqueristas/www

Just find a way to respond with that payload when a `GET http://localhost:9000/api/v2/activities` request comes in.

**Comment by krainboltgreene** [comment]
In this case replace client/index.js:68 with `STORE.sync`, and define `const STORE = new JsonApiDataStore()` somewhere above `main`.

**Comment by beauby** [comment]
Closing this as it seemed to be a usage error rather than a bug. Feel free to reopen if needed.
