### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by beauby** [beauby/jsonapi-datastore#32]
Hi peeps,

As you may have noticed, I haven't had much time to take care of this project lately. Anyone interested in helping me maintaining it?

Cheers,

Lucas

**Comment by buren** [comment]
Hi @beauby, I might. 

Would be nice to have a chat before though :) maybe I can contact you in the ams slack think I've seen you there 

/jacob

**Comment by EricPMulligan** [comment]
@buren, I may be able to help as well. See #33.

**Comment by beauby** [comment]
Hi guys, apologies for the late reply, I just came back from Australia. Let's set up a skype/hangout to discuss all that!

**Comment by EricPMulligan** [comment]
Considering that I'm in Eastern Time and you're both in Europe, how about some time this upcoming Saturday or Sunday?

**Comment by buren** [comment]
Sunday would work for me.

**Comment by beauby** [comment]
Sunday works for me as well 👌

On Tuesday, 21 June 2016, Jacob Burenstam <notifications@github.com> wrote:

> Sunday would work for me.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/beauby/jsonapi-datastore/issues/32#issuecomment-227411710>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACHPYmEuvtIl2BXS5QK0k4GzSq6EIGV1ks5qN8migaJpZM4Ig4x_>
> .
>


-- 
Lucas Hosseini
lucas.hosseini@gmail.com

**Comment by buren** [comment]
Sunday at 11.00 CEST?

**Comment by EricPMulligan** [comment]
As I'm only interested in helping out and I haven't yet contributed any code, feel free to go ahead without me.

**Comment by beauby** [comment]
Sorry guys, we never quite got to do this call. If any or both of you guys are still interested, we can give it another shot!

**Comment by niksy** [comment]
@beauby this is a great little project and it would be shame to go to waste, so I’ve started modifications on my fork which incorporate most of the pull requests and open issues: https://github.com/niksy/jsonapi-datastore

Is anyone still interested in maintainer position? I would be willing in taking collaborative effort.

**Comment by copasetickid** [comment]
@niksy I took at look at your fork and you seem to be actively working on getting it 1.0 If you looking for or need help, I'm interested in doing so and wanted to know how I can help?

I think this could be useful to an angular project I'm working on and can be easily dropped into other projects using different frameworks once it's complete

**Comment by beauby** [comment]
Cool, if @niksy's fork is the main active one I'll put a notice on the README to redirect people there.

**Comment by copasetickid** [comment]
@niksy  Also I expressed an interest in maintaining this  when I reached out for the status of this to @beauby  [here](https://github.com/beauby/jsonapi-datastore/issues/29)

**Comment by beauby** [comment]
Thanks for @copasetickid for stepping up – jsonapi-datastore has a new maintainer, and should get moving again soon!
