### ISSUE TITLE
ES6 import with Browserify

### ISSUE THREAD

**Issue by mwpastore** [beauby/jsonapi-datastore#5]
I'm having a heck of a time trying to import jsonapi-datastore into my Ember application using Browserify. Can someone help me with the syntax? `new JsonApiDataStore()` yields the following when I try:

```javascript
import { JsonApiDataStore } from 'npm:jsonapi-datastore';
```

Gives me `npm_jsonapi_datastore.JsonApiDataStore is not a function`, and:

```javascript
import JsonApiDataStore from 'npm:jsonapi-datastore';
```

Gives me `JsonApiDataStore.default is not a function`, and:

```javascript
import * as JsonApiDataStore from 'npm:jsonapi-datastore';
```

Gives me `JsonApiDataStore is not a function`. 

Thanks in advance for any suggestions...

**Comment by beauby** [comment]
Hi @mwpastore, the situation should become much easier once #4 gets merged (which will be really soon).

**Comment by mwpastore** [comment]
Great! Thank you!

**Comment by beauby** [comment]
@mwpastore This should be fixed now that #4 has been merged. Could you confirm?

**Comment by krainboltgreene** [comment]
Just tried it with latest npm, still not working :(

**Comment by beauby** [comment]
Glad to hear that! May I close the issue?

**Comment by krainboltgreene** [comment]
Yes! Well at least for me.

**Comment by beauby** [comment]
Great, closing then, feel free to reopen if needed.
