### ISSUE TITLE
Automated NPM Publishing

### ISSUE THREAD

**Issue by rubencosta** [beauby/jsonapi-datastore#9]
Hi, When trying to use this library by getting it from NPM I noticed that the package that was published was not updated. 
You should `npm publish` to update the package and since you are using Travis CI you could automate the NPM publishing (http://docs.travis-ci.com/user/deployment/npm/)

**Comment by beauby** [comment]
Thanks @rubencosta. Will publish a new npm/bower version right away, and will look into automating publishing in a bit.

**Comment by beauby** [comment]
Closed by #19. Thanks for raising this!
